"use client";

import { useState } from "react";
import { BentoCard } from "@/components/ui/bento";
import { Moon, Sun, Monitor, Sliders, Globe, Shield } from "lucide-react";
import { useTheme } from "next-themes";
import { cn } from "@/lib/utils";

const THEME_OPTIONS = [
  { id: "light", label: "Light", icon: Sun },
  { id: "dark", label: "Dark", icon: Moon },
  { id: "system", label: "System", icon: Monitor },
];

export default function SettingsPage() {
  const { theme, setTheme } = useTheme();
  const [apiUrl, setApiUrl] = useState("http://localhost:8000");

  return (
    <div className="p-8 max-w-2xl">
      <div className="mb-8">
        <h1 className="text-headline text-[rgb(var(--text-primary))]">Settings</h1>
        <p className="text-body text-[rgb(var(--text-secondary))] mt-1">
          Customize your Verdict workspace
        </p>
      </div>

      <div className="space-y-5">
        {/* Appearance */}
        <BentoCard className="p-6">
          <div className="flex items-center gap-2 mb-5">
            <Sliders className="w-4 h-4 text-[rgb(var(--text-tertiary))]" />
            <p className="text-subtitle font-semibold text-[rgb(var(--text-primary))]">Appearance</p>
          </div>
          <div className="space-y-4">
            <div>
              <p className="text-small font-medium text-[rgb(var(--text-primary))] mb-3">Theme</p>
              <div className="flex gap-2">
                {THEME_OPTIONS.map(({ id, label, icon: Icon }) => (
                  <button
                    key={id}
                    onClick={() => setTheme(id)}
                    className={cn(
                      "flex-1 flex flex-col items-center gap-2 py-4 rounded-xl border text-caption font-medium transition-all duration-200",
                      theme === id
                        ? "border-[rgb(var(--accent-primary))]/60 bg-[rgb(var(--accent-primary))]/8 text-[rgb(var(--accent-primary))]"
                        : "border-[rgb(var(--border-default))] text-[rgb(var(--text-secondary))] hover:border-[rgb(var(--border-strong))] hover:text-[rgb(var(--text-primary))]"
                    )}
                  >
                    <Icon className="w-4 h-4" />
                    {label}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </BentoCard>

        {/* API Configuration */}
        <BentoCard className="p-6">
          <div className="flex items-center gap-2 mb-5">
            <Globe className="w-4 h-4 text-[rgb(var(--text-tertiary))]" />
            <p className="text-subtitle font-semibold text-[rgb(var(--text-primary))]">API Configuration</p>
          </div>
          <div>
            <p className="text-small font-medium text-[rgb(var(--text-primary))] mb-2">Backend URL</p>
            <div className="flex gap-3">
              <input
                type="text"
                value={apiUrl}
                onChange={(e) => setApiUrl(e.target.value)}
                className="flex-1 px-4 py-2.5 rounded-lg border border-[rgb(var(--border-default))] bg-[rgb(var(--bg-elevated))] text-[rgb(var(--text-primary))] text-small font-mono focus:border-[rgb(var(--accent-primary))]/60 outline-none transition-colors"
              />
              <button className="px-4 py-2.5 rounded-lg bg-[rgb(var(--accent-primary))]/10 border border-[rgb(var(--accent-primary))]/20 text-[rgb(var(--accent-primary))] text-small font-medium hover:bg-[rgb(var(--accent-primary))]/20 transition-colors">
                Save
              </button>
            </div>
            <p className="text-caption text-[rgb(var(--text-tertiary))] mt-2">
              The FastAPI backend URL. Defaults to localhost:8000.
            </p>
          </div>
        </BentoCard>

        {/* Privacy notice */}
        <BentoCard className="p-6">
          <div className="flex items-center gap-2 mb-3">
            <Shield className="w-4 h-4 text-[rgb(var(--text-tertiary))]" />
            <p className="text-subtitle font-semibold text-[rgb(var(--text-primary))]">About Verdict</p>
          </div>
          <p className="text-small text-[rgb(var(--text-secondary))] leading-relaxed">
            Verdict is an AI-powered equity research platform. All research reports are generated by AI agents and should not be treated as financial advice. Research data is sourced from Yahoo Finance, Google News, and Tavily. All AI analysis is performed via the configured LLM provider.
          </p>
          <div className="mt-4 flex items-center gap-4">
            <div>
              <p className="text-caption text-[rgb(var(--text-tertiary))]">Frontend Version</p>
              <p className="text-small font-mono text-[rgb(var(--text-primary))]">1.0.0</p>
            </div>
            <div>
              <p className="text-caption text-[rgb(var(--text-tertiary))]">Backend</p>
              <p className="text-small font-mono text-[rgb(var(--text-primary))]">{apiUrl}</p>
            </div>
          </div>
        </BentoCard>
      </div>
    </div>
  );
}
