from pydantic import BaseModel, Field


class ResearchReport(BaseModel):
    """
    Structured research report generated by the Writer Agent.
    """

    company_overview: str = Field(
        description="Brief overview of the company and its business."
    )

    financial_analysis: str = Field(
        description="Analysis of the company's financial metrics."
    )

    recent_news_summary: str = Field(
        description="Summary of important recent news."
    )

    opportunities: str = Field(
        description="Potential growth opportunities."
    )

    risks: str = Field(
        description="Potential business and investment risks."
    )

    investment_outlook: str = Field(
        description="Final investment outlook and conclusion."
    )